# Generated by Django 4.1.3 on 2022-11-08 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_id', models.CharField(max_length=100)),
                ('business_name', models.CharField(max_length=100)),
                ('yelp_business_id', models.CharField(blank=True, max_length=45, null=True)),
                ('city', models.CharField(max_length=100, unique=True)),
                ('state', models.CharField(max_length=100, unique=True)),
                ('address', models.CharField(blank=True, max_length=100, null=True)),
                ('postal_code', models.CharField(blank=True, max_length=15, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('business_stars', models.DecimalField(blank=True, decimal_places=2, max_digits=10)),
                ('business_review_count', models.IntegerField(blank=True, null=True)),
                ('is_open', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Business Information',
                'verbose_name_plural': "Business's Information",
                'db_table': 'business',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('city_id', models.AutoField(primary_key=True, serialize=False)),
                ('city_name', models.CharField(max_length=45, unique=True)),
            ],
            options={
                'verbose_name': 'Business city',
                'verbose_name_plural': "Business's city",
                'db_table': 'city',
                'ordering': ['city_name'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('review_id', models.AutoField(primary_key=True, serialize=False)),
                ('stars', models.DecimalField(blank=True, decimal_places=2, max_digits=10)),
                ('date_created', models.DateField(blank=True)),
                ('review_text', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Review made by user about a business',
                'verbose_name_plural': 'Reviews made by users about various businesses',
                'db_table': 'review',
                'ordering': ['business', 'user', 'stars', 'date_created', 'review_text'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('state_id', models.AutoField(primary_key=True, serialize=False)),
                ('state_abbrev', models.CharField(max_length=10, unique=True)),
            ],
            options={
                'verbose_name': 'State where the Business is located',
                'verbose_name_plural': 'State where the Business is located',
                'db_table': 'state',
                'ordering': ['state_abbrev'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=45, unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('review_count', models.IntegerField()),
                ('yelper_since', models.DateField(blank=True)),
                ('average_stars', models.DecimalField(blank=True, decimal_places=2, max_digits=10)),
                ('yelp_user_id', models.CharField(blank=True, max_length=45)),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'db_table': 'user',
                'ordering': ['username', 'review_count', 'average_stars', 'yelper_since'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='YelpInputModel',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('term', models.CharField(blank=True, max_length=100)),
                ('location', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'db_table': 'yelpinputmodel',
                'managed': True,
            },
        ),
    ]
