# Generated by Django 4.1.3 on 2022-11-13 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='business',
            options={'managed': True, 'ordering': ['business_name', 'business_stars', 'is_open'], 'verbose_name': 'Business Information', 'verbose_name_plural': "Business's Information"},
        ),
    ]
